# Treinamento

### Carregando Arquivo de Treinamento (.csv)

In [50]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/idylicaro/IA---2020.1---Exerc-cio---06---Rede-Neural-Artificial/main/diabetes.csv'
base_Treinamento = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("---------------------------------")
print("Dados dos Pacientes - TREINAMENTO")
print("---------------------------------")
#print(base_Treinamento)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Treinamento[:, 0:8])

print("----------------------------")
print("Classificação Supervisionada")
print("----------------------------")
print(base_Treinamento[:, 8])

---------------------------------
Dados dos Pacientes - TREINAMENTO
---------------------------------
---------------------------------
Atributos de Entrada
---------------------------------
[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
----------------------------
Classificação Supervisionada
----------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 1. 0.

### Pré-processamento de Dados

In [51]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
# lb = preprocessing.LabelBinarizer()
# no = preprocessing.Normalizer()

escaler = preprocessing.MinMaxScaler()

# Pregnancies
pregnancies = escaler.fit_transform(np.array(base_Treinamento[:, 0]).reshape(-1,1))

# Glucose
glucose = escaler.fit_transform(np.array(base_Treinamento[:, 1]).reshape(-1,1))

# BloodPressure
bloodPressure = escaler.fit_transform(np.array(base_Treinamento[:, 2]).reshape(-1,1))

# SkinThickness
skinThickness = escaler.fit_transform(np.array(base_Treinamento[:, 3]).reshape(-1,1))

# Insulin
insulin = escaler.fit_transform(np.array(base_Treinamento[:, 4]).reshape(-1,1))

# BMI
BMI = escaler.fit_transform(np.array(base_Treinamento[:, 5]).reshape(-1,1))

# DiabetesPedigreeFunction
diabetesPedigreeFunction = escaler.fit_transform(np.array(base_Treinamento[:, 6]).reshape(-1,1))

# Age
age = escaler.fit_transform(np.array(base_Treinamento[:, 7]).reshape(-1,1))

# Separete classes
classes = base_Treinamento[:, 8]

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((pregnancies, glucose, bloodPressure, skinThickness, insulin, BMI, diabetesPedigreeFunction, age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)

print("----------------------------------------")
print("Classificação Supervisionada - Numéricos")
print("----------------------------------------")
diagnostico_norm = np.hstack((classes))
print(diagnostico_norm)

--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.35294118 0.74371859 0.59016393 ... 0.50074516 0.23441503 0.48333333]
 [0.05882353 0.42713568 0.54098361 ... 0.39642325 0.11656704 0.16666667]
 [0.47058824 0.91959799 0.52459016 ... 0.34724292 0.25362938 0.18333333]
 ...
 [0.29411765 0.6080402  0.59016393 ... 0.390462   0.07130658 0.15      ]
 [0.05882353 0.63316583 0.49180328 ... 0.4485842  0.11571307 0.43333333]
 [0.05882353 0.46733668 0.57377049 ... 0.45305514 0.10119556 0.03333333]]
----------------------------------------
Classificação Supervisionada - Numéricos
----------------------------------------
[1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1.

### Treinamento do Neurônio Perceptron

In [52]:
from sklearn.linear_model import Perceptron
# Treinamento do Perceptron a partir dos atributos de entrada e classificações
modelo = Perceptron()
modelo.fit(atributos_norm, diagnostico_norm)

# Acurácia do modelo, que é : 1 - (predições erradas / total de predições)
# Acurácia do modelo: indica uma performance geral do modelo. 
# Dentre todas as classificações, quantas o modelo classificou corretamente;
# (VP+VN)/N
print('Acurácia: %.3f' % modelo.score(atributos_norm, diagnostico_norm))

Acurácia: 0.736


### ----------------------------------------------------------------------------

# Validação do Aprendizado 

### Predição a partir de base de dados (.csv)

In [54]:
import pandas as pd
# Carregando dados do arquivo CSV
url = 'https://raw.githubusercontent.com/idylicaro/IA---2020.1---Exerc-cio---06---Rede-Neural-Artificial/main/testes.csv'
base_Testes = pd.read_csv(url,sep=',', encoding = 'latin1').values
print("----------------------------")
print("Dados dos Pacientes - TESTES")
print("----------------------------")
print(base_Testes)
print("---------------------------------")

# Extração dos Atributos a serem utilizadas pela rede
print("Atributos de Entrada")
print("---------------------------------")
print(base_Testes[:, 0:8])

----------------------------
Dados dos Pacientes - TESTES
----------------------------
[[6.00e+00 1.48e+02 7.20e+01 3.50e+01 0.00e+00 3.36e+01 6.27e-01 5.00e+01
  1.00e+00]
 [1.00e+00 8.50e+01 6.60e+01 2.90e+01 0.00e+00 2.66e+01 3.51e-01 3.10e+01
  0.00e+00]
 [8.00e+00 1.83e+02 6.40e+01 0.00e+00 0.00e+00 2.33e+01 6.72e-01 3.20e+01
  1.00e+00]
 [1.00e+00 8.90e+01 6.60e+01 2.30e+01 9.40e+01 2.81e+01 1.67e-01 2.10e+01
  0.00e+00]]
---------------------------------
Atributos de Entrada
---------------------------------
[[6.00e+00 1.48e+02 7.20e+01 3.50e+01 0.00e+00 3.36e+01 6.27e-01 5.00e+01]
 [1.00e+00 8.50e+01 6.60e+01 2.90e+01 0.00e+00 2.66e+01 3.51e-01 3.10e+01]
 [8.00e+00 1.83e+02 6.40e+01 0.00e+00 0.00e+00 2.33e+01 6.72e-01 3.20e+01]
 [1.00e+00 8.90e+01 6.60e+01 2.30e+01 9.40e+01 2.81e+01 1.67e-01 2.10e+01]]


### Pré-processamento de Dados

In [55]:
import numpy as np 
from sklearn import preprocessing

# Binarizador de rótulo
# lb = preprocessing.LabelBinarizer()
# no = preprocessing.Normalizer()

escaler = preprocessing.MinMaxScaler()

# Pregnancies
pregnancies = escaler.fit_transform(np.array(base_Testes[:, 0]).reshape(-1,1))

# Glucose
glucose = escaler.fit_transform(np.array(base_Testes[:, 1]).reshape(-1,1))

# BloodPressure
bloodPressure = escaler.fit_transform(np.array(base_Testes[:, 2]).reshape(-1,1))

# SkinThickness
skinThickness = escaler.fit_transform(np.array(base_Testes[:, 3]).reshape(-1,1))

# Insulin
insulin = escaler.fit_transform(np.array(base_Testes[:, 4]).reshape(-1,1))

# BMI
BMI = escaler.fit_transform(np.array(base_Testes[:, 5]).reshape(-1,1))

# DiabetesPedigreeFunction
diabetesPedigreeFunction = escaler.fit_transform(np.array(base_Testes[:, 6]).reshape(-1,1))

# Age
age = escaler.fit_transform(np.array(base_Testes[:, 7]).reshape(-1,1))

#Concatenação de Atributos (Colunas) 
atributos_norm = np.column_stack((pregnancies, glucose, bloodPressure, skinThickness, insulin, BMI, diabetesPedigreeFunction, age))
print("--------------------------------")
print("Atributos de Entrada - Numéricos")
print("--------------------------------")
print(atributos_norm)



--------------------------------
Atributos de Entrada - Numéricos
--------------------------------
[[0.71428571 0.64285714 1.         1.         0.         1.
  0.91089109 1.        ]
 [0.         0.         0.25       0.82857143 0.         0.32038835
  0.36435644 0.34482759]
 [1.         1.         0.         0.         0.         0.
  1.         0.37931034]
 [0.         0.04081633 0.25       0.65714286 1.         0.46601942
  0.         0.        ]]


### Predição da Base

In [56]:
base_Predicao = modelo.predict((atributos_norm))
print("Classificações: ", base_Predicao)

Classificações:  [1. 0. 1. 0.]
